asyncapi: 2.6.0
info:
  title: Query Repository DeviceConfiguration
  version: 0.1.0
servers:
  production:
    url: 127.0.0.1:5678
    protocol: amqp
    description: Query Repository.
    bindings:
      amqp:
        exchange:
          name: query_repository
channels:
  DeviceQueue:
    publish:
      message:
        $ref: '#/components/messages/DeviceMessage'
    bindings:
      amqp:
        routingKey: deviceQueue
components:
  messages:
    DeviceMessage:
      payload:
        type: object
        $id: DevicePayload
        properties:
          id:
            type: integer
          name:
            type: string
          ip:
            type: string
          costmodel:
            type: string
          rpuCapabilities:
            type: string
          ports:
            type: array
            items:
              type: object
              $id: PortPayload
              properties:
                number:
                  type: integer
                ip:
                  type: string
                internalIp:
                  type: string
                datastream:
                  type: integer




